// src/component/TSTable.jsx
import React, { useEffect, useRef } from 'react';
import * as echarts from 'echarts';

const Detaile = ({place, data, forestCount, handleIndex}) => {
    // 创建图表容器的引用
    const chartRef = useRef(null);
    const chartInstance = useRef(null);
    const indexRef = useRef(0);

    const fortrun = () => {
        if(indexRef.current === 0) return;
        indexRef.current = indexRef.current - 1;
        handleIndex(indexRef.current);
    }

    const backtrun = () => {
        if(indexRef.current === 24/forestCount - 1) return;
        indexRef.current = indexRef.current + 1;
        handleIndex(indexRef.current);
    }


    useEffect(() => {
        // 初始化图表
        const now = new Date().getHours();
        if (chartRef.current) {
            chartInstance.current = echarts.init(chartRef.current);
            // 配置项
            const option = {
                title: {
                    text: `24H预测`
                },
                tooltip: {
                    trigger: 'axis',
                    formatter: function (params) {
                        let result = `${params[0].axisValue}<br/>`;
                        params.forEach(function (param) {
                            result += `${param.seriesName}: ${param.value} ${
                                param.seriesIndex === 0 ? '°C' : param.seriesIndex === 1 ? '%' : '%'
                            }<br/>`;
                        });
                        return result;
                    }
                },
                legend: {
                    data: ["温度", "湿度", "降水概率"],
                    selectedMode: false,
                },
                xAxis: {
                    type: 'category',
                    boundaryGap: false,
                    data: new Array(forestCount).fill(0).map((_, index) => {
                        const hour = (now + index + indexRef.current * forestCount) % 24;
                        return `${hour}:00`;
                    }),
                    axisLine: {
                        // onZero: false, // 不在零点显示
                        lineStyle: {
                            color: '#000000'
                        }
                    },
                    axisTick: {
                        show: true,
                        alignWithLabel: true
                    },
                    axisLabel: {
                        show: true
                    }
                },
                yAxis: [
                    {
                        type: 'value',
                        name: '°C',
                        position: 'left',
                        max: Math.max(...data[0])+ 2,
                        min: Math.min(...data[0]) - 3, // 设置Y轴的起始位置为-10
                        scale: false, // 设置为false，让min和max生效
                        axisTick: {
                            show: true,
                        },
                        axisLabel: {
                            formatter:  function(value) {
                                return value + '°C';
                            }
                        },
                        axisLine: {
                            show: true,
                            lineStyle: {
                                color: 'rgb(0,0,0)' // Y轴2的颜色
                            }
                        },
                        splitLine: {
                            show: false // 隐藏 Y 轴的基准线
                        }
                    },
                    {
                        type: 'value',
                        position: 'right',
                        name: '%',
                        max: Math.max(...data[1]) + 10,
                        min: Math.min(...data[1]),
                        axisTick: {
                            show: true,
                            alignWithLabel: true
                        },
                        axisLabel: {
                            formatter: '{value}'
                        },
                        axisLine: {
                            show: false,
                        },
                        splitLine: {
                            show: false // 隐藏 Y 轴的基准线
                        }
                    },
                    {
                        type: 'value',
                        name: '',
                        position: 'right',
                        max: Math.max(...data[2]) + 10,
                        min: Math.min(...data[2]),
                        axisLine: {
                            show: false // 隐藏 Y 轴线
                        },
                        axisTick: {
                            show: false // 隐藏刻度线
                        },
                        axisLabel: {
                            show: false // 隐藏刻度值
                        },
                        splitLine: {
                            show: false // 隐藏 Y 轴的基准线
                        }
                    }
                ],
                series: [
                    {
                        name: '温度',
                        type: 'line',
                        yAxisIndex: 0, // 使用第一个 Y 轴
                        data: data[0],
                        itemStyle: {
                            color: '#ff0000'
                        },
                        symbolSize: 0, // 节点大小
                        // areaStyle: {
                        //     color: new echarts.graphic.LinearGradient(0, 0, 0, 1, [
                        //       {
                        //         offset: 0,
                        //         color: 'rgba(58,77,233,0.8)'
                        //       },
                        //       {
                        //         offset: 1,
                        //         color: 'rgba(58,77,233,0.3)'
                        //       }
                        //     ])
                        //   },
                        smooth: true,
                    },
                    {
                        name: '湿度',
                        type: 'line',
                        yAxisIndex: 1, // 使用第二个 Y 轴
                        data: data[1],
                        symbolSize: 0, // 节点大小
                        itemStyle: {
                            color: '#00ff00'
                        },
                        smooth: true,
                    },
                    {
                        name: '降水概率',
                        type: 'line',
                        yAxisIndex: 2, // 使用第三个 Y 轴
                        data: data[2],
                        symbolSize: 0, // 节点大小
                        itemStyle: {
                            color: '#0000ff'
                        },
                        smooth: true,
                    }
                ]
            };

            // 应用配置项
            chartInstance.current.setOption(option);

            // 窗口大小变化时调整图表大小
            window.addEventListener('resize', () => {
                chartInstance.current.resize();
            });

            // 组件卸载时销毁图表
            return () => {
                window.removeEventListener('resize', () => {
                    chartInstance.current.resize();
                });
                chartInstance.current.dispose();
            };
        }
    },[place,data]);



    return (
        <>
            <div ref={chartRef} className='w-full h-full'></div>
            <div onClick={fortrun} className='absolute z-10 top-1/3 left-5 cursor-pointer text-white text-3xl'>{'<'}</div>
            <div onClick={backtrun} className='absolute z-10 top-1/3 right-5 cursor-pointer text-white text-3xl'>{'>'}</div>
        </>
    );
};

export default Detaile;

// src/component/TSTable.vue
<template>
    <div style="width: 100%; height: 100%;">
      <div ref="chartRef" class="w-full h-full"></div>
      <div
        @click="fortrun"
        class="absolute z-10 top-1/3 left-5 cursor-pointer text-white text-3xl"
      >
        {{ left }}
      </div>
      <div
        @click="backtrun"
        class="absolute z-10 top-1/3 right-5 cursor-pointer text-white text-3xl"
      >
        >
      </div>
    </div>
  </template>
  
  <script>
  import * as echarts from "echarts";
  
  export default {
    name: "DetailChart",
    props: {
      place: {
        type: String,
        required: true,
      },
      data: {
        type: Array,
        required: true,
      },
      forestCount: {
        type: Number,
        required: true,
      },
      handleIndex: {
        type: Function,
        required: true,
      },
    },
    data() {
      return {
        chartInstance: null,
        indexRef: 0,
        left:'<'
      };
    },
    watch: {
      place: {
        immediate: true,
        handler() {
          this.initChart();
        },
      },
      data: {
        immediate: true,
        handler() {
          this.initChart();
        },
      },
    },
    mounted() {
      this.initChart();
      window.addEventListener("resize", this.resizeChart);
    },
    beforeDestroy() {
      window.removeEventListener("resize", this.resizeChart);
      if (this.chartInstance) {
        this.chartInstance.dispose();
      }
    },
    methods: {
      initChart() {
        console.log(this.chartInstance,this.$refs.chartRef);
        if (this.chartInstance) {
          this.chartInstance.dispose();
        }
        this.chartInstance = echarts.init(this.$refs.chartRef);
  
        const now = new Date().getHours();
  
        const option = {
          title: {
            text: `24H预测`,
          },
          tooltip: {
            trigger: "axis",
            formatter: function (params) {
              let result = `${params[0].axisValue}<br/>`;
              params.forEach(function (param) {
                result += `${param.seriesName}: ${param.value} ${
                  param.seriesIndex === 0 ? "°C" : param.seriesIndex === 1 ? "%" : "%"
                }<br/>`;
              });
              return result;
            },
          },
          legend: {
            data: ["温度", "湿度", "降水概率"],
            selectedMode: false,
          },
          xAxis: {
            type: "category",
            boundaryGap: false,
            data: new Array(this.forestCount)
              .fill(0)
              .map((_, index) => {
                const hour = (now + index + this.indexRef * this.forestCount) % 24;
                return `${hour}:00`;
              }),
            axisLine: {
              lineStyle: {
                color: "#000000",
              },
            },
            axisTick: {
              show: true,
              alignWithLabel: true,
            },
            axisLabel: {
              show: true,
            },
          },
          yAxis: [
            {
              type: "value",
              name: "°C",
              position: "left",
              max: Math.max(...this.data[0]) + 2,
              min: Math.min(...this.data[0]) - 3,
              scale: false,
              axisTick: {
                show: true,
              },
              axisLabel: {
                formatter: function (value) {
                  return value + "°C";
                },
              },
              axisLine: {
                show: true,
                lineStyle: {
                  color: "rgb(0,0,0)",
                },
              },
              splitLine: {
                show: false,
              },
            },
            {
              type: "value",
              position: "right",
              name: "%",
              max: Math.max(...this.data[1]) + 10,
              min: Math.min(...this.data[1]),
              axisTick: {
                show: true,
                alignWithLabel: true,
              },
              axisLabel: {
                formatter: "{value}",
              },
              axisLine: {
                show: false,
              },
              splitLine: {
                show: false,
              },
            },
            {
              type: "value",
              name: "",
              position: "right",
              max: Math.max(...this.data[2]) + 10,
              min: Math.min(...this.data[2]),
              axisLine: {
                show: false,
              },
              axisTick: {
                show: false,
              },
              axisLabel: {
                show: false,
              },
              splitLine: {
                show: false,
              },
            },
          ],
          series: [
            {
              name: "温度",
              type: "line",
              yAxisIndex: 0,
              data: this.data[0],
              itemStyle: {
                color: "#ff0000",
              },
              symbolSize: 0,
              smooth: true,
            },
            {
              name: "湿度",
              type: "line",
              yAxisIndex: 1,
              data: this.data[1],
              itemStyle: {
                color: "#00ff00",
              },
              symbolSize: 0,
              smooth: true,
            },
            {
              name: "降水概率",
              type: "line",
              yAxisIndex: 2,
              data: this.data[2],
              itemStyle: {
                color: "#0000ff",
              },
              symbolSize: 0,
              smooth: true,
            },
          ],
        };
  
        this.chartInstance.setOption(option);
      },
      resizeChart() {
        if (this.chartInstance) {
          this.chartInstance.resize();
        }
      },
      fortrun() {
        if (this.indexRef === 0) return;
        this.indexRef = this.indexRef - 1;
        this.handleIndex(this.indexRef);
      },
      backtrun() {
        if (this.indexRef === 24 / this.forestCount - 1) return;
        this.indexRef = this.indexRef + 1;
        this.handleIndex(this.indexRef);
      },
    },
  };
  </script>
